import logging
import asyncio
import json
import discord
from discord import app_commands
from discord.ext import commands
from datetime import datetime, timezone
from typing import Optional, Dict, Any
from urllib import request

from config import TEBEX_KEYS, TEBEX_BASE_URL

class Migration(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    def tebex_request(self, api_key: str, method: str, endpoint: str, data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        url = f"{TEBEX_BASE_URL}{endpoint}"
        headers = {
            "X-Tebex-Secret": api_key,
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        
        body = json.dumps(data).encode("utf-8") if data else None
        req = request.Request(url, headers=headers, data=body, method=method)
        
        try:
            with request.urlopen(req, timeout=30) as resp:
                response_data = resp.read()
                return json.loads(response_data.decode("utf-8"))
        except Exception as e:
            logging.error(f"Tebex API error: {e}")
            raise

    @app_commands.command(name="migrate", description="Generate a Tebex gift card for migration.")
    @app_commands.describe(
        server="The server to generate the gift card for.",
        total_in_usd="The total value in USD for the gift card."
    )
    @app_commands.choices(server=[
        app_commands.Choice(name="ATM", value="ATM"),
        app_commands.Choice(name="Nomi", value="Nomi"),
        app_commands.Choice(name="Inf", value="Inf"),
        app_commands.Choice(name="SB4", value="SB4"),
        app_commands.Choice(name="GTNH", value="GTNH"),
    ])
    async def migrate(self, interaction: discord.Interaction, server: app_commands.Choice[str], total_in_usd: float) -> None:
        allowed_role_id = 1442244395452862465
        if not isinstance(interaction.user, discord.Member) or not any(role.id == allowed_role_id for role in interaction.user.roles):
            await interaction.response.send_message("You do not have permission to use this command.", ephemeral=True)
            return

        target_channel_id = 1443397300910030919
        
        # Defer response to avoid timeout
        await interaction.response.defer(ephemeral=True)

        api_key = TEBEX_KEYS.get(server.value)
        if not api_key:
             await interaction.followup.send(f"Configuration error: No API key found for {server.name}.", ephemeral=True)
             return

        try:
            # Create Gift Card via Tebex API
            payload = {
                "amount": total_in_usd,
                "note": f"Migration for {interaction.user} ({interaction.user.id})"
            }
            
            response = await asyncio.to_thread(self.tebex_request, api_key, "POST", "/gift-cards", payload)
            
            if not response or "data" not in response:
                 gift_card = response.get("data", response)
            else:
                 gift_card = response["data"]

            code = gift_card.get("code")
            if not code:
                 raise ValueError("No code returned from Tebex API")

            # Create Embed
            embed = discord.Embed(
                title=f"Migration Gift Card ({server.name})",
                description=(
                    "Hello your rank has been moved over to store credit, login into our store and purchase a new Premium rank, "
                    "please use this code to use your balance:\n\n"
                    f"```\n{code}\n```\n"
                    "During checkout there will be an option for Apply Coupons & Gift Cards enter the code above to use your balance."
                ),
                color=0xF1C40F, # Gold color
                timestamp=datetime.now(timezone.utc)
            )
            embed.set_image(url="https://cdn.discordapp.com/attachments/1443912118314205196/1443933287486849154/image.png?ex=692c30aa&is=692adf2a&hm=354fb4a3b0f88cb00e1ea172d24cf1625640737e4cc2cfeace4b3eeeedae4517&")
            embed.add_field(name="Amount", value=f"${total_in_usd:.2f} USD", inline=True)
            embed.add_field(name="Generated By", value=interaction.user.mention, inline=True)
            embed.set_footer(text="Tebex Migration")

            # Send to target channel
            target_channel = interaction.client.get_channel(target_channel_id) or await interaction.client.fetch_channel(target_channel_id)
            if target_channel:
                await target_channel.send(embed=embed)
                await interaction.followup.send(f"Gift card generated and sent to {target_channel.mention}.", ephemeral=True)
            else:
                await interaction.followup.send("Gift card generated, but could not find the target channel.", ephemeral=True)

        except Exception as e:
            logging.exception("Failed to generate gift card")
            await interaction.followup.send(f"Failed to generate gift card: {str(e)}", ephemeral=True)

async def setup(bot: commands.Bot) -> None:
    await bot.add_cog(Migration(bot))
